name: release

on:
  create:
    tags:

jobs:
  release:
    name: release on github
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v1
      # get release tag into `RELEASE_VERSION` env var
      run: |
        echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

    - name: setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: zip the source code
      run: |
        zip konnek-gcp-$RELEASE_VERSION.zip *.go go.*

    - name: upload the source code
      run: |
        gsutil cp konnek-gcp-$RELEASE_VERSION.zip gs://konnek-gcp/